### ISSUE TITLE
java.lang.NullPointerException 	at org.netbeans.modules.bugtracking.commons.FileToRepoMappingStorage.cutTrailingSlashes(FileToRepoMappingStorage.java:196)

### ISSUE THREAD

**Issue by markiewb** [junichi11/netbeans-github-issues-plugin#15]
* Click on a issue link in the history view
* create a new repository (choose from an existing one in the dropdown fetched from github)
* Click connect/OK

```
java.lang.NullPointerException
	at org.netbeans.modules.bugtracking.commons.FileToRepoMappingStorage.cutTrailingSlashes(FileToRepoMappingStorage.java:196)
	at org.netbeans.modules.bugtracking.commons.FileToRepoMappingStorage.setAssociation(FileToRepoMappingStorage.java:163)
	at org.netbeans.modules.bugtracking.commons.FileToRepoMappingStorage.setFirmAssociation(FileToRepoMappingStorage.java:81)
	at org.netbeans.modules.bugtracking.BugtrackingOwnerSupport.setFirmAssociation(BugtrackingOwnerSupport.java:218)
	at org.netbeans.modules.bugtracking.ui.issue.IssueAction$3$1.run(IssueAction.java:190)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
Caused: org.openide.util.RequestProcessor$SlowItem: task failed due to
	at org.openide.util.RequestProcessor.post(RequestProcessor.java:419)
	at org.netbeans.modules.bugtracking.ui.issue.IssueAction$3.run(IssueAction.java:167)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
[catch] at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

```
Using the 0.0.5-dev version

**Comment by markiewb** [comment]
Once it is wrong configured. It happens everytime when trying to interact with
```
java.lang.NullPointerException
	at org.netbeans.modules.bugtracking.commons.FileToRepoMappingStorage.cutTrailingSlashes(FileToRepoMappingStorage.java:196)
	at org.netbeans.modules.bugtracking.BugtrackingOwnerSupport.getRepositoryByUrl(BugtrackingOwnerSupport.java:419)
	at org.netbeans.modules.bugtracking.BugtrackingOwnerSupport.getRepositoryForContext(BugtrackingOwnerSupport.java:274)
	at org.netbeans.modules.bugtracking.BugtrackingOwnerSupport.getRepository(BugtrackingOwnerSupport.java:150)
	at org.netbeans.modules.bugtracking.ui.issue.IssueAction$3$1.run(IssueAction.java:182)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
Caused: org.openide.util.RequestProcessor$SlowItem: task failed due to
	at org.openide.util.RequestProcessor.post(RequestProcessor.java:419)
	at org.netbeans.modules.bugtracking.ui.issue.IssueAction$3.run(IssueAction.java:167)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
[catch] at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by junichi11** [comment]
I've fixed. 

Could you try to test it ?

https://github.com/junichi11/netbeans-github-issues-plugin/releases/tag/v0.0.6

**Comment by junichi11** [comment]
Please try to set a property of your repository. (i.e. Click connect button > OK button)

**Comment by junichi11** [comment]
I'll close this. If you have a problem, please feel free to reopen it.

**Comment by markiewb** [comment]
I haven't seen this issue so far (using it some minutes)
0.0.6-dev

**Comment by markiewb** [comment]
FYI: The NPE within NB is also fixed now
https://netbeans.org/bugzilla/show_bug.cgi?id=249959#c6

**Comment by junichi11** [comment]
Thanks :+1:
