### ISSUE TITLE
Periodical NullPointerException when task repository loses connection

### ISSUE THREAD

**Issue by AlexFalappa** [junichi11/netbeans-github-issues-plugin#52]
I am getting periodical NPEs without doing anything in particular. I suspect it is something linked to a network connection, cause I am now in a different setup than usual. 

However it would be nice to guard against it.

Here's the stack trace:
```
java.lang.NullPointerException
	at com.junichi11.netbeans.modules.github.issues.query.GitHubQuery.refresh(GitHubQuery.java:239)
	at com.junichi11.netbeans.modules.github.issues.query.GitHubQueryProvider.refresh(GitHubQueryProvider.java:96)
	at com.junichi11.netbeans.modules.github.issues.query.GitHubQueryProvider.refresh(GitHubQueryProvider.java:52)
	at org.netbeans.modules.bugtracking.QueryImpl.refresh(QueryImpl.java:128)
	at org.netbeans.modules.bugtracking.tasks.dashboard.DashboardRefresher.refreshDashboard(DashboardRefresher.java:152)
	at org.netbeans.modules.bugtracking.tasks.dashboard.DashboardRefresher.access$400(DashboardRefresher.java:59)
	at org.netbeans.modules.bugtracking.tasks.dashboard.DashboardRefresher$1.run(DashboardRefresher.java:85)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1443)
	at org.netbeans.modules.openide.util.GlobalLookup.execute(GlobalLookup.java:68)
	at org.openide.util.lookup.Lookups.executeWith(Lookups.java:303)
[catch] at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2058)
```

It seems that after invoking the properties of the GitHub task repository and clicking on _Connect_ the problem should go away.

**Comment by junichi11** [comment]
Thanks for reporting it!

**Comment by junichi11** [comment]
Fixed. It should be OK. 
https://github.com/junichi11/netbeans-github-issues-plugin/releases/tag/v0.3.3

Thanks.

**Comment by AlexFalappa** [comment]
@junichi11 thanks for the swift reaction!
