### ISSUE TITLE
ClassFormatError: Absent Code attribute

### ISSUE THREAD

**Issue by cbm64chris** [junichi11/netbeans-github-issues-plugin#53]
Appreciate this has not yet been built for 11.1 but heads up to an issue;

Right Click on Task Repositories and Select GitHub from the dropdown yields the following ClassFormatError error.

Mac OS X, 10.14.6, x86_64
Java HotSpot(TM) 64-Bit Server VM, 12.0.1+12, Java(TM) SE Runtime Environment, 12.0.1+12
Apache NetBeans IDE 11.1
netbeans-github-issues-plugin: 0.5.0

```
java.lang.ClassFormatError: Absent Code attribute in method that is not native or abstract in class file com/junichi11/netbeans/modules/github/issues/repository/ui/GitHubRepositoryPanel$1
	at java.base/java.lang.ClassLoader.defineClass1(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1016)
	at org.netbeans.JarClassLoader.doLoadClass(JarClassLoader.java:286)
	at org.netbeans.ProxyClassLoader.selfLoadClass(ProxyClassLoader.java:234)
	at org.netbeans.ProxyClassLoader.loadClass(ProxyClassLoader.java:162)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:521)
	at com.junichi11.netbeans.modules.github.issues.repository.ui.GitHubRepositoryPanel.initComponents(GitHubRepositoryPanel.java:354)
	at com.junichi11.netbeans.modules.github.issues.repository.ui.GitHubRepositoryPanel.<init>(GitHubRepositoryPanel.java:89)
	at com.junichi11.netbeans.modules.github.issues.repository.GitHubRepositoryController.getPanel(GitHubRepositoryController.java:131)
	at com.junichi11.netbeans.modules.github.issues.repository.GitHubRepositoryController.getComponent(GitHubRepositoryController.java:73)
	at org.netbeans.modules.bugtracking.ui.selectors.RepositoryFormPanel.displayFormPanel(RepositoryFormPanel.java:226)
	at org.netbeans.modules.bugtracking.ui.selectors.RepositoryFormPanel.displayForm(RepositoryFormPanel.java:146)
	at org.netbeans.modules.bugtracking.ui.selectors.RepositorySelectorBuilder.displayRepositoryForm(RepositorySelectorBuilder.java:554)
	at org.netbeans.modules.bugtracking.ui.selectors.RepositorySelectorBuilder.displayRepositoryForm(RepositorySelectorBuilder.java:546)
	at org.netbeans.modules.bugtracking.ui.selectors.RepositorySelectorBuilder.displayRepositoryForm(RepositorySelectorBuilder.java:528)
	at org.netbeans.modules.bugtracking.ui.selectors.RepositorySelectorBuilder.itemSelected(RepositorySelectorBuilder.java:486)
	at org.netbeans.modules.bugtracking.ui.selectors.RepositorySelectorBuilder.itemStateChanged(RepositorySelectorBuilder.java:479)
	at java.desktop/javax.swing.JComboBox.fireItemStateChanged(JComboBox.java:1227)
	at java.desktop/javax.swing.JComboBox.selectedItemChanged(JComboBox.java:1288)
	at java.desktop/javax.swing.JComboBox.contentsChanged(JComboBox.java:1335)
	at java.desktop/javax.swing.AbstractListModel.fireContentsChanged(AbstractListModel.java:123)
	at java.desktop/javax.swing.DefaultComboBoxModel.setSelectedItem(DefaultComboBoxModel.java:94)
	at java.desktop/javax.swing.JComboBox.setSelectedItem(JComboBox.java:579)
	at java.desktop/javax.swing.JComboBox.setSelectedIndex(JComboBox.java:624)
	at java.desktop/javax.swing.plaf.basic.BasicComboPopup$Handler.mouseReleased(BasicComboPopup.java:907)
	at java.desktop/java.awt.AWTEventMulticaster.mouseReleased(AWTEventMulticaster.java:298)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/javax.swing.plaf.basic.BasicComboPopup$1.processMouseEvent(BasicComboPopup.java:551)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
[catch] at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:117)
	at java.desktop/java.awt.WaitDispatchSupport$2.run(WaitDispatchSupport.java:190)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:235)
	at java.desktop/java.awt.WaitDispatchSupport$4.run(WaitDispatchSupport.java:233)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:310)
	at java.desktop/java.awt.WaitDispatchSupport.enter(WaitDispatchSupport.java:233)
	at java.desktop/java.awt.Dialog.show(Dialog.java:1070)
	at org.netbeans.core.windows.services.NbPresenter.superShow(NbPresenter.java:1060)
	at org.netbeans.core.windows.services.NbPresenter.doShow(NbPresenter.java:1110)
	at org.netbeans.core.windows.services.NbPresenter.run(NbPresenter.java:1082)
	at org.netbeans.core.windows.services.NbPresenter.run(NbPresenter.java:105)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.doEventAccess(NbMutexEventProvider.java:115)
	at org.netbeans.modules.openide.util.NbMutexEventProvider$Event.readAccess(NbMutexEventProvider.java:75)
	at org.netbeans.modules.openide.util.LazyMutexImplementation.readAccess(LazyMutexImplementation.java:71)
	at org.openide.util.Mutex.readAccess(Mutex.java:193)
	at org.netbeans.core.windows.services.NbPresenter.show(NbPresenter.java:1067)
	at java.desktop/java.awt.Component.show(Component.java:1716)
	at java.desktop/java.awt.Component.setVisible(Component.java:1663)
	at java.desktop/java.awt.Window.setVisible(Window.java:1021)
	at java.desktop/java.awt.Dialog.setVisible(Dialog.java:1005)
	at org.netbeans.core.windows.services.DialogDisplayerImpl$1AWTQuery.showDialog(DialogDisplayerImpl.java:241)
	at org.netbeans.core.windows.services.DialogDisplayerImpl.notify(DialogDisplayerImpl.java:257)
	at org.netbeans.core.windows.services.DialogDisplayerImpl.notify(DialogDisplayerImpl.java:148)
	at org.netbeans.modules.bugtracking.ui.selectors.SelectorPanel.create(SelectorPanel.java:46)
	at org.netbeans.modules.bugtracking.ui.selectors.RepositorySelector.create(RepositorySelector.java:56)
	at org.netbeans.modules.bugtracking.util.BugtrackingUtil.createRepository(BugtrackingUtil.java:52)
	at org.netbeans.modules.bugtracking.api.Util.createRepository(Util.java:162)
	at org.netbeans.modules.bugtracking.bridge.nodes.BugtrackingRootNode$1.actionPerformed(BugtrackingRootNode.java:92)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at java.desktop/javax.swing.AbstractButton$Handler.actionPerformed(AbstractButton.java:2308)
	at java.desktop/javax.swing.DefaultButtonModel.fireActionPerformed(DefaultButtonModel.java:405)
	at java.desktop/javax.swing.DefaultButtonModel.setPressed(DefaultButtonModel.java:262)
	at java.desktop/javax.swing.AbstractButton.doClick(AbstractButton.java:369)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI.doClick(BasicMenuItemUI.java:1020)
	at java.desktop/com.apple.laf.AquaMenuItemUI.doClick(AquaMenuItemUI.java:157)
	at java.desktop/javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(BasicMenuItemUI.java:1064)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6632)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3342)
	at java.desktop/java.awt.Component.processEvent(Component.java:6397)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2762)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4840)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:772)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:715)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:745)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:743)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:389)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:742)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:136)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)

```

**Comment by junichi11** [comment]
@cbm64chris 
Please use v0.3.3 temporarily : https://github.com/junichi11/netbeans-github-issues-plugin/releases/tag/v0.3.3

**Comment by junichi11** [comment]
@cbm64chris 
Just rebuilt it: https://github.com/junichi11/netbeans-github-issues-plugin/releases/tag/v0.5.1 
It should be OK.
Unfortunately, I can't login to the Plugin Portal. (I'm asking Jirka about it.) So, I can't upload the new nbm there soon.
