### ISSUE TITLE
Exception when creating a new task

### ISSUE THREAD

**Issue by markiewb** [junichi11/netbeans-github-issues-plugin#8]
![image](https://cloud.githubusercontent.com/assets/1857095/5864930/1b7d3e38-a286-11e4-8e1f-272d43d502db.png)

```
java.lang.NullPointerException
	at org.netbeans.modules.bugtracking.commons.FileToRepoMappingStorage.cutTrailingSlashes(FileToRepoMappingStorage.java:196)
	at org.netbeans.modules.bugtracking.commons.FileToRepoMappingStorage.setAssociation(FileToRepoMappingStorage.java:163)
	at org.netbeans.modules.bugtracking.commons.FileToRepoMappingStorage.setLooseAssociation(FileToRepoMappingStorage.java:87)
	at org.netbeans.modules.bugtracking.BugtrackingOwnerSupport.setLooseAssociation(BugtrackingOwnerSupport.java:248)
	at org.netbeans.modules.bugtracking.RepositoryImpl.setLooseAssociation(RepositoryImpl.java:476)
	at org.netbeans.modules.bugtracking.RepositoryImpl.createNewIssue(RepositoryImpl.java:264)
	at org.netbeans.modules.bugtracking.ui.issue.IssueTopComponent$5.run(IssueTopComponent.java:401)
	at org.openide.util.RequestProcessor$Task.run(RequestProcessor.java:1423)
	at org.openide.util.RequestProcessor$Processor.run(RequestProcessor.java:2033)
Caused: org.openide.util.RequestProcessor$SlowItem: task failed due to
	at org.openide.util.RequestProcessor.post(RequestProcessor.java:419)
	at org.netbeans.modules.bugtracking.ui.issue.IssueTopComponent.onRepoSelected(IssueTopComponent.java:383)
	at org.netbeans.modules.bugtracking.ui.issue.IssueTopComponent.initNewIssue(IssueTopComponent.java:186)
	at org.netbeans.modules.bugtracking.ui.issue.IssueAction$2$1.run(IssueAction.java:129)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:744)
	at java.awt.EventQueue.access$400(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:697)
	at java.awt.EventQueue$3.run(EventQueue.java:691)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$1.doIntersectionPrivilege(ProtectionDomain.java:75)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:714)
	at org.netbeans.core.TimableEventQueue.dispatchEvent(TimableEventQueue.java:159)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
[catch] at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by markiewb** [comment]
Product Version: NetBeans IDE 8.0.2 (Build 201411181905)
Updates: Updates available
Java: 1.8.0_05; Java HotSpot(TM) 64-Bit Server VM 25.5-b02
Runtime: Java(TM) SE Runtime Environment 1.8.0_05-b13
System: Windows 7 version 6.1 running on amd64; Cp1252; en_US (nb)

**Comment by junichi11** [comment]
Umm, I can't reproduce it now...

@tstupka 
Is this an issue of Bugtracking modules? Is my implementation is wrong?

**Comment by junichi11** [comment]
@markiewb I've released a new version. Can you reproduce it yet?

**Comment by markiewb** [comment]
No. I cannot reproduce it anymore using 0.0.5dev. Closing this issue

**Comment by junichi11** [comment]
Thanks for your confirmation :)
